name: config-folders/credentialsUsernamePassword_config
on:
  workflow_dispatch:
env:
#   # This item has no matching transformer
#   FOO:

# Write the environment variables manually as below
env:
  FOO_PSW: ${{ secrets.FOO_PSW }}
  FOO_USR: ${{ vars.FOO_USR }}
  FOO: ${{ secrets.FOO }}

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - name: sh
      shell: bash
      run: echo "FOO is $FOO"
    - name: sh
      shell: bash
      run: echo "FOO_USR is $FOO_USR"
    - name: sh
      shell: bash
      run: echo "FOO_PSW is $FOO_PSW"
    - name: sh
      shell: bash
      run: echo $FOO > foo.txt
      working-directory: combined
    - name: sh
      shell: bash
      run: echo $FOO_PSW > foo_psw.txt
    - name: sh
      shell: bash
      run: echo $FOO_USR > foo_usr.txt
#     # This item has no matching transformer
#     - archive:
#       - key: includes
#         value:
#           isLiteral: true
#           value: "**/*.txt"
#   Create a custom transformer to upload the artifacts as below for not imported items as below
    - name: Archive files
      uses: actions/upload-artifact@v2
      with:
        name: foo-files
        path: |
          combined/foo.txt
          combined/foo_usr.txt
          combined/foo_psw.txt
