name: config-folders/postUnstable_config
on:
  workflow_dispatch:
jobs:
  Hello:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
#     # 'script' was not transformed because there is no suitable equivalent in GitHub Actions
#     - name: script
#       arguments:
#       - key: scriptBlock
#         value:
#           isLiteral: true
#           value: currentBuild.result = "UNSTABLE"
#   Create a custom script with environment variable for not imported items as below  
    - name: echo message
      run: |
        echo "hello"
        # Use an environment variable to set the build status
        echo "::set-env name=BUILD_STATUS::UNSTABLE"

  Post-Build:
    if: always()
    name: Post Build
    runs-on: ubuntu-latest
    needs:
    - Hello
    steps:
    - name: snapshot post build workflow status
      run: echo "unstable=${{ contains(needs.*.result,'failure') && !contains(needs.*.result,'cancelled') }}" >> $GITHUB_OUTPUT
      id: __post_build
    - name: echo message
      run: echo UNSTABLE runs after ALWAYS
      if: steps.__post_build.outputs.unstable == 'true'
    - name: echo message
      run: echo I ALWAYS run first
      if: always()
