name: config-folders/credentialsMixedEnvironment_config
on:
  workflow_dispatch:
#env:
#  SOME_VAR: SOME VALUE
#   # This item has no matching transformer
#   CRED1:
#  INBETWEEN: Something in between
#   # This item has no matching transformer
#   CRED2:
#   # This item has no matching transformer
#   OTHER_VAR: '"${{ env.SOME_VAR }}"'
  env:
    SOME_VAR: "SOME VALUE"
    INBETWEEN: "Something in between"
    OTHER_VAR: ${{ env.SOME_VAR }}
jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - name: sh
      shell: bash
      run: echo "SOME_VAR is $SOME_VAR"
    - name: sh
      shell: bash
      run: echo "INBETWEEN is $INBETWEEN"
    - name: sh
      shell: bash
      run: echo "OTHER_VAR is $OTHER_VAR"
#     # This item has no matching transformer
#     - archive:
#       - key: includes
#         value:
#           isLiteral: true
#           value: "**/*.txt"

#   Create a custom transformer as below for not imported items as below 
    - name: Create Credentials Files
      env:
        CRED1: ${{ secrets.CRED1 }}
        CRED2: ${{ secrets.CRED2 }}
      run: |
        echo $CRED1 > cred1.txt
        echo $CRED2 > cred2.txt

    - name: Archive Text Files
      uses: actions/upload-artifact@v2
      with:
        name: text-files
        path: |
          cred1.txt
          cred2.txt
