name: config-folders/parametersBooleanRecursivePromotion_config
on:
  workflow_dispatch:
jobs:
  promote:
    #if:
#       # Unsupported condition(s) [expression]
    runs-on: ubuntu-latest
    if: ${{ github.run_number % 2 == 1 }}    
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
#     # This action relies on the workflow '${currentBuild.getProjectName()}.yml' being present in this repository (change the repository parameter if the workflow is in a different repository).
#     # Ensure that the workflow exists, has the workflow_dispatch trigger, and has matching input parameters.
#     - name: Trigger workflow
#       uses: octokit/request-action@v2.1.7
#       env:
#         GITHUB_TOKEN: "${{ secrets.WORKFLOW_TRIGGER_TOKEN }}"
#       with:
#         route: POST /repos/:repository/actions/workflows/:workflow_id/dispatches
#         repository: "${{ github.repository }}"
#         workflow_id: "${currentBuild.getProjectName()}.yml"
#         ref: "${{ github.ref }}"
#   Create a custom script using curl command for not imported items as below 
      - name: Run promotion job
        run: |
          curl -X POST \
            -H 'Content-Type: application/json' \
            -d '{"parameter": [{"name":"SIMUL", "value":"${{ env.SIMUL }}" }]} \
            https://jenkins.example.com/job/${{ github.repository }}/${{ github.run_id }}/build
