name: config-folders/toolsBuildPluginParentPOM_config
on:
  workflow_dispatch:

env:
  M2_HOME: /usr/local/apache-maven-3.1.0
  JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Set up Maven
      uses: maven/setup-maven@v1
      with:
        maven-version: '3.1.0'
        maven-options: '-Dmaven.test.failure.ignore=true'

    - name: Build with Maven
      run: mvn clean verify

    - name: Archive Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: target/
