name: config-folders/environmentInStage_config
on:
  workflow_dispatch:
env:
  FOO: PIPELINE
jobs:
  local:
    runs-on: ubuntu-latest
    env:
      BAR: STAGE
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - name: sh
      shell: bash
      run: echo "FOO is $FOO and BAR is $BAR"
  global:
    runs-on: ubuntu-latest
    needs: local
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - name: sh
      shell: bash
      run: echo "FOO is $FOO and BAR is $BAR"