name: config-folders/whenExpressionSkip_config
on:
  workflow_dispatch:
jobs:
  Hello:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - name: echo message
      run: echo Hello
  Always_Skip:
#    if:
#       # Unsupported condition(s) [expression]
    name: Always Skip
    runs-on: ubuntu-latest
    needs: Hello
# # create the below Custom Condition that was not imported from jenkins        
    if: ${{ false }}
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - name: echo message
      run: echo World