name: config-folders/whenEnvVarCondition_config
on:
  workflow_dispatch:
env:
#   # This item has no matching transformer
#   FOO: '"${currentBuild.getNumber() % 2}"'

# Create a custom environment variable for not imported variables 
  FOO: ${{ github.run_number % 2 }}
jobs:
  Hello:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - name: echo message
      run: echo Hello
  Evaluate_FOO:
  #  if:
#       # Unsupported condition(s) [environment]
    name: Evaluate FOO
    runs-on: ubuntu-latest
    needs: Hello
# Create a custom condition to call the env variable    
    if: env.FOO == '1'
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - name: echo message
      run: echo World