name: add-migration-issue

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      ci-tool:
        type: choice
        description: CI/CD tool to use
        options:
          - Jenkins
          - Gitlab
          - CircleCI
          - TravisCI
          
jobs:
  add-issueops:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install @actions/github @octokit/rest
      - name: Create Issue
        id: create-issueops
        uses: actions/github-script@v6
        with:
          script: |
            const { Octokit } = require('@octokit/rest');
            const octokit = new Octokit({ auth: '${{ secrets.ISSUE_OPS_ACTION_IMPORTER_TOKEN }}' })
            const response = await octokit.request('POST /repos/${{ vars.ISSUE_OPS_ACTION_IMPORTER_REPO }}/issues', {
              title: '${{ inputs.ci-tool }} Pipeline Importer for Repo ${{ github.repository }}',
              labels: ['${{ inputs.ci-tool }}'],
              headers: {'X-GitHub-Api-Version': '2022-11-28'}
            })
            console.log('Created issue number:', response.data.number);
            console.log('::set-output name=issue_number::' + response.data.number);
      - name: Create or Update Variable
        run: |
          if curl -L -X GET -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.ISSUE_OPS_ACTION_IMPORTER_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/${{ github.repository }}/actions/variables/${{ inputs.ci-tool }}_ISSUE_ID | grep -q 'Not Found'; then
              curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.ISSUE_OPS_ACTION_IMPORTER_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/${{ github.repository }}/actions/variables -d '{"name":"${{ inputs.ci-tool }}_ISSUE_ID","value":"${{ steps.create-issueops.outputs.issue_number }}"}'
          else
              curl -L -X PATCH -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.ISSUE_OPS_ACTION_IMPORTER_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/${{ github.repository }}/actions/variables/${{ inputs.ci-tool }}_ISSUE_ID -d '{"name":"${{ inputs.ci-tool }}_ISSUE_ID","value":"${{ steps.create-issueops.outputs.issue_number }}"}'
          fi	
           
 
